#!/usr/bin/env python3
"""One-time helper used to author data/games.json. Not required to run the
site — kept here for reference if you want to bulk-regenerate entries."""
import json, os

GENRE_ACCENT = {
    "Metroidvania": ("#3ee6c4", "#0c8f7a"),
    "Roguelike": ("#ff7a45", "#b23c1f"),
    "Action RPG": ("#a970ff", "#5b2a9e"),
    "RPG": ("#7c8cff", "#3a3f9e"),
    "JRPG": ("#ff5fa8", "#9e2a6b"),
    "Turn-Based RPG": ("#ffb84d", "#a6631a"),
    "Action Adventure": ("#ffcf3f", "#a6791a"),
    "Platformer": ("#4dd0ff", "#1a6fa6"),
    "3D Platformer": ("#4dd0ff", "#1a6fa6"),
    "Co-op Platformer": ("#4dd0ff", "#1a6fa6"),
    "Co-op Action Adventure": ("#4dd0ff", "#1a6fa6"),
    "Survival Horror": ("#ff3b3b", "#7a1414"),
    "Tactical Shooter": ("#ffd23f", "#8a6a12"),
    "VR Shooter": ("#39ff88", "#0f8a45"),
    "Puzzle": ("#7ee0ff", "#1b7fa6"),
    "Life Simulation": ("#ffa6d9", "#a6417c"),
    "Farming Simulation": ("#8fe36a", "#3f8a1f"),
    "Sandbox Survival": ("#c8ff4d", "#6f9e13"),
    "MMORPG": ("#4d7fff", "#1f3f9e"),
}

GAMES = [
  dict(slug="hollow-knight-silksong", title="Hollow Knight: Silksong", tagline="Ascend the kingdom of Pharloom as Hornet.",
       release="2025-09-04", genres=["Metroidvania"], platforms=["PC","Switch","Switch 2","PS4","PS5","Xbox One","Xbox Series X|S"],
       developer="Team Cherry", publisher="Team Cherry", yt=("KTd_qTWnfyk","Hollow Knight: Silksong - Full Game Walkthrough"),
       lore="Captured and carried far from Hallownest, Hornet wakes in the haunted, silk-choked kingdom of Pharloom. Compelled by a mysterious summons ringing from its highest peak, she cuts her way upward through crumbling cathedrals, bogs, and bell-towns tangled in an ancient, decaying faith. Old gods, needle-cults, and a fractured royal line all have a claim on the kingdom's fate, and on the ringing bell that seems to be calling her by name."),
  dict(slug="hades-2", title="Hades II", tagline="Melinoë hunts Chronos through the Underworld and beyond.",
       release="2025-09-25", genres=["Roguelike","Action RPG"], platforms=["PC","Switch"],
       developer="Supergiant Games", publisher="Supergiant Games", yt=("q_ajc87CDs0","HADES 2 Gameplay Walkthrough FULL GAME [4K 60FPS PC ULTRA] - No Commentary"),
       lore="Centuries after the House of Hades fell to the Titan of Time, the witch-princess Melinoë trains in exile at a hidden crossroads, gathering allies from the old pantheon for one purpose: reaching Chronos and ending his rule before he unmakes the family she has left. Each attempt carries her from the Underworld's shifting caverns to the surface world above, deepening a war between gods, witches, and time itself."),
  dict(slug="donkey-kong-bananza", title="Donkey Kong Bananza", tagline="Smash straight down through a world of layered terrain.",
       release="2025-07-17", genres=["3D Platformer"], platforms=["Switch 2"],
       developer="Nintendo EPD", publisher="Nintendo", yt=("2Y1FQBw9_9E","Donkey Kong Bananza FULL COMPLETE 100% Game Walkthrough"),
       lore="When a golden vein of Bananium sets off a chain of destruction, Donkey Kong smashes down through Earth's crust layer by layer, teaming up with the strange, tunnel-dwelling Pauline to chase it to the planet's core. Rival crews of banana-hungry rogues want the same prize, turning the descent into a running battle across wildly different sub-surface worlds."),
  dict(slug="death-stranding-2", title="Death Stranding 2: On the Beach", tagline="Sam Porter Bridges reconnects a shattered continent once more.",
       release="2025-06-26", genres=["Action Adventure"], platforms=["PS5"],
       developer="Kojima Productions", publisher="Sony Interactive Entertainment", yt=("aifSQ3Dklyc","DEATH STRANDING 2: ON THE BEACH Full Walkthrough Part 1 (No Commentary) @1440p Ultra 60Fps"),
       lore="Years after reconnecting America, Sam Porter Bridges is pulled out of quiet retirement for a new delivery network stretching across Mexico and beyond, as the mysterious organization Drawbridge pushes an agenda that puts him at odds with the peace he helped build. Otherworldly Beached Things, fractured nations, and old ghosts from the first Death Stranding all resurface as Sam carries the world's last threads of connection on his back."),
  dict(slug="clair-obscur-expedition-33", title="Clair Obscur: Expedition 33", tagline="A doomed expedition marches against the Paintress's countdown.",
       release="2025-04-24", genres=["Turn-Based RPG"], platforms=["PC","PS5","Xbox Series X|S"],
       developer="Sandfall Interactive", publisher="Sandfall Interactive", yt=("w5yb8AqU2Lw","Clair Obscur: Expedition 33 – Full Walkthrough (No Commentary, 4K60FPS)"),
       lore="Once a year, a godlike Paintress paints a number on her monolith, and everyone in the city of Lumière who has reached that age turns to ash and vanishes. Gustave and the sixty-seven other members of Expedition 33 set out from the last generation of survivors to cross the sea to her tower and end the painting for good, knowing full well that expeditions before them never returned."),
  dict(slug="split-fiction", title="Split Fiction", tagline="Two rival writers get trapped inside their own stories.",
       release="2025-03-06", genres=["Co-op Action Adventure"], platforms=["PC","PS5","Xbox Series X|S"],
       developer="Hazelight Studios", publisher="Electronic Arts", yt=("wZuSX6lMORk","SPLIT FICTION Gameplay Walkthrough FULL GAME 100% [4K 60FPS] - No Commentary"),
       lore="Sci-fi author Mio and fantasy author Zoe sign on with a publisher whose machine promises to bring their stories to life, only to end up fused together and trapped inside a glitching simulation built from both their imaginations. Forced to cooperate, the pair fight, fly, and freefall through wildly different genres, each level bouncing between Zoe's dragons and Mio's neon dystopias as they search for a way back out."),
  dict(slug="monster-hunter-wilds", title="Monster Hunter Wilds", tagline="Track colossal beasts across the shifting Forbidden Lands.",
       release="2025-02-28", genres=["Action RPG"], platforms=["PC","PS5","Xbox Series X|S"],
       developer="Capcom", publisher="Capcom", yt=("dwRYF9o-xTE","MONSTER HUNTER WILDS Gameplay Walkthrough FULL GAME (4K 60FPS) No Commentary"),
       lore="A lone, wounded boy found wandering the desert leads the Hunters Guild's research commission into the Forbidden Lands, a region whose seasons shift the entire ecosystem beneath hunters' feet. As the commission tracks the boy's origins, ancient and unclassified monsters begin surfacing, hinting that the Forbidden Lands hide something the Guild has never catalogued before."),
  dict(slug="metaphor-refantazio", title="Metaphor: ReFantazio", tagline="An outcast prince's rise, decided by a kingdom-wide election.",
       release="2024-10-11", genres=["JRPG"], platforms=["PC","PS5","PS4","Xbox Series X|S"],
       developer="Studio Zero (Atlus)", publisher="Sega", yt=("BV7DL2xlRDM","METAPHOR REFANTAZIO Gameplay Walkthrough FULL GAME (HD) No Commentary 100%"),
       lore="In the fantasy kingdom of Euchronia, the assassinated king's dying decree throws the throne open to whoever the people elect, and a despised, otherized protagonist enters the race guided only by a strange book and the will-turned-monster Archetypes it grants him. Racing against rival candidates and a countdown to save a cursed friend, he travels a continent built on prejudice and myth, testing whether imagination can actually reshape a society."),
  dict(slug="astro-bot", title="Astro Bot", tagline="Rebuild the shattered PS5 mothership, one galaxy at a time.",
       release="2024-09-06", genres=["3D Platformer"], platforms=["PS5"],
       developer="Team Asobi", publisher="Sony Interactive Entertainment", yt=("gUl8FdkBgpg","ASTRO BOT - Full Game 100% Walkthrough"),
       lore="When space pirates blast the PlayStation mothership apart and scatter its crew of bots across the galaxy, Astro sets off alone to recover them, planet by whimsical planet. Each world doubles as a playable tribute to PlayStation's own history, turning the rescue mission into a victory-lap tour of decades of games."),
  dict(slug="black-myth-wukong", title="Black Myth: Wukong", tagline="A nameless monk retraces the legend of the Monkey King.",
       release="2024-08-20", genres=["Action RPG"], platforms=["PC","PS5","Xbox Series X|S"],
       developer="Game Science", publisher="Game Science", yt=("T4DFKOlrXCQ","BLACK MYTH WUKONG Gameplay Walkthrough FULL GAME [4K 60FPS] - No Commentary"),
       lore="Long after the Monkey King renounced his title and vanished, a nameless wandering monk called the Destined One sets out across a fractured mythic China to recover the six relics of his shattered power. Drawing directly from the classic Journey to the West, the road puts him against the same demons, gods, and old grudges that once tested the legend himself."),
  dict(slug="final-fantasy-7-rebirth", title="Final Fantasy VII Rebirth", tagline="Cloud and AVALANCHE chase Sephiroth beyond Midgar.",
       release="2024-02-29", genres=["Action RPG"], platforms=["PS5","PC"],
       developer="Square Enix", publisher="Square Enix", yt=("Il2YOK4_luc","FINAL FANTASY 7: REBIRTH Full Walkthrough Gameplay – PS5 Pro 4K 60FPS No Commentary"),
       lore="Having escaped the fallen plate city of Midgar, Cloud and the remnants of AVALANCHE follow Sephiroth's trail across an open continent of ruins, resorts, and Shinra-scarred wilderness, with the fate of the planet's lifestream hanging on what they find. Old memories keep surfacing to blur what Cloud actually remembers of his past with Sephiroth and Zack, and Aerith's visions of the future grow harder for the party to ignore."),
  dict(slug="baldurs-gate-3", title="Baldur's Gate 3", tagline="Escape a mind flayer ship, and the parasite it left behind.",
       release="2023-08-03", genres=["RPG"], platforms=["PC","PS5","Xbox Series X|S","macOS"],
       developer="Larian Studios", publisher="Larian Studios", yt=("UCxFhfQFaec","BALDUR'S GATE 3 Gameplay Walkthrough FULL GAME (4K 60FPS) No Commentary"),
       lore="Infected with a mind flayer tadpole during an illithid ship's crash over the Sword Coast, a small band of the infected banded together to find a cure before the parasite transforms them, or before it grants them power they can't safely refuse. Their search drags them into a cult's plot to unleash an ancient elder brain beneath Baldur's Gate, with companions, gods, and old betrayals shaping which ending the city gets."),
  dict(slug="spider-man-2", title="Marvel's Spider-Man 2", tagline="Peter and Miles share the mantle against Kraven and Venom.",
       release="2023-10-20", genres=["Action Adventure"], platforms=["PS5"],
       developer="Insomniac Games", publisher="Sony Interactive Entertainment", yt=("RWXMAb9APh8","Marvel's Spider-Man 2 Gameplay Walkthrough FULL GAME - No Commentary"),
       lore="With Peter Parker and Miles Morales both swinging as Spider-Man, New York faces the arrival of Kraven the Hunter, whose global manhunt for the ultimate prey collides with a symbiote that binds itself to Peter and begins twisting him toward the person he's trying not to become. Balancing a shared identity, a spreading black suit, and Harry Osborn's uncertain recovery pushes both Spider-Men toward very different breaking points."),
  dict(slug="zelda-tears-of-the-kingdom", title="The Legend of Zelda: Tears of the Kingdom", tagline="Link rebuilds a fallen kingdom from the sky down.",
       release="2023-05-12", genres=["Action Adventure"], platforms=["Switch"],
       developer="Nintendo EPD", publisher="Nintendo", yt=("rye3wVDyI5g","ZELDA TEARS OF THE KINGDOM Gameplay Walkthrough FULL GAME (4K ULTRA HD) No Commentary"),
       lore="A corrupted secret beneath Hyrule Castle awakens an ancient evil and flings Link into the sky islands above, stripping Zelda from his side and scattering the kingdom's history across ruins on the surface, sky, and a newly opened Depths below. Piecing together dragon tears of memory, Link has to rebuild Hyrule's shattered alliances before Ganondorf's return finishes what the corruption started."),
  dict(slug="resident-evil-4-remake", title="Resident Evil 4", tagline="Leon Kennedy walks into a village that isn't right.",
       release="2023-03-24", genres=["Survival Horror"], platforms=["PC","PS5","PS4","Xbox Series X|S"],
       developer="Capcom", publisher="Capcom", yt=("KMadSaqc338","RESIDENT EVIL 4 REMAKE Gameplay Walkthrough FULL GAME (8K 60FPS RTX) No Commentary"),
       lore="Six years after Raccoon City, government agent Leon Kennedy tracks the president's kidnapped daughter to a remote Spanish village whose residents have been turned into cult-controlled, parasite-driven killers. What starts as a rescue mission unravels into a conspiracy involving the shadowy organization Los Iluminados and a parasite designed to control minds on a global scale."),
  dict(slug="diablo-4", title="Diablo IV", tagline="Lilith returns to Sanctuary to reclaim what she made.",
       release="2023-06-06", genres=["Action RPG"], platforms=["PC","PS5","PS4","Xbox Series X|S","Xbox One"],
       developer="Blizzard Entertainment", publisher="Blizzard Entertainment", yt=("1KFp_2ME1XE","DIABLO 4 Full Gameplay Walkthrough / No Commentary 【FULL GAME】4K 60FPS Ultra HD"),
       lore="Decades of famine and unrest have left Sanctuary vulnerable when Lilith, the demonic co-creator of humanity, tears her way back into the world through a blood-soaked cult ritual. A wandering Wanderer, marked since birth, is drawn into the fight to stop her from remaking Sanctuary as her own dominion, with the fractured Horadrim order caught in the middle."),
  dict(slug="counter-strike-2", title="Counter-Strike 2", tagline="Counter-Terrorists and Terrorists clash over bomb sites, round after round.",
       release="2023-09-27", genres=["Tactical Shooter"], platforms=["PC"],
       developer="Valve", publisher="Valve", yt=("2ssBLr8i52E","The ULTIMATE CS2 Beginner Guide (2026)"),
       lore="Rebuilt on Valve's Source 2 engine, Counter-Strike 2 carries forward the series' long-running, story-light standoff between a Counter-Terrorist unit and a Terrorist faction fighting over hostages and bomb sites on maps drawn from two decades of competitive play. There's no campaign to speak of: the drama is generated round by round, economy by economy, by whoever's on the server with you."),
  dict(slug="god-of-war-ragnarok", title="God of War Ragnarök", tagline="Kratos and Atreus can't outrun the coming Ragnarök.",
       release="2022-11-09", genres=["Action Adventure"], platforms=["PS5","PS4"],
       developer="Santa Monica Studio", publisher="Sony Interactive Entertainment", yt=("ixllGOX0Evw","GOD OF WAR RAGNAROK Gameplay Walkthrough FULL GAME PS5 4K 60FPS No Commentary"),
       lore="With Fimbulwinter dragging into its third year and Odin hunting them across the Nine Realms, Kratos tries to keep his son Atreus from a prophesied fate while Atreus grows increasingly determined to face it head-on. Old family, new alliances among the realms' desperate survivors, and the inevitability of Ragnarök force father and son to finally decide what kind of gods, if any, they want to become."),
  dict(slug="elden-ring", title="Elden Ring", tagline="A Tarnished returns to claim the shattered Elden Ring.",
       release="2022-02-25", genres=["Action RPG"], platforms=["PC","PS5","PS4","Xbox Series X|S","Xbox One"],
       developer="FromSoftware", publisher="Bandai Namco", yt=("WVF4GccrX6E","ELDEN RING Full Game Walkthrough - No Commentary (4K 60 FPS)"),
       lore="The Elden Ring has been shattered and its Great Runes scattered among demigods whose feuding has left the Lands Between in ruin, guided by no clear order since. Exiled long ago and stripped of grace, a Tarnished answers a summons back across the Lands Between to gather the shards, challenge the demigods, and become Elden Lord in whatever way the fractured order allows."),
  dict(slug="horizon-forbidden-west", title="Horizon Forbidden West", tagline="Aloy chases a dying world's last hope westward.",
       release="2022-02-18", genres=["Action RPG"], platforms=["PS5","PS4","PC"],
       developer="Guerrilla Games", publisher="Sony Interactive Entertainment", yt=("-xixDMXq1xU","Horizon Forbidden West: Complete Edition Full Walkthrough Part 1 (No Commentary) @1440p Ultra 60Fps"),
       lore="With a mysterious blight killing the last plant life keeping Earth's ecosystem alive, Aloy pushes further west into unmapped tribal lands to find the source and, if she can, a functioning copy of the old terraforming system GAIA. New tribes, rebuilt Old Earth technology, and machines more dangerous than anything she's fought complicate a mission that's really a race against total ecological collapse."),
  dict(slug="it-takes-two", title="It Takes Two", tagline="A splitting couple gets turned into dolls and forced to cooperate.",
       release="2021-03-26", genres=["Co-op Platformer"], platforms=["PC","PS5","PS4","Xbox"],
       developer="Hazelight Studios", publisher="Electronic Arts", yt=("iBKPF4Yd6jE","It Takes Two – Full Game Walkthrough (No Commentary | 2K 60FPS Co-Op)"),
       lore="On the night Cody and May decide to divorce, their daughter's tearful wish and a book of home-brewed relationship magic turns both parents into living dolls. Guided by an obnoxiously chipper self-help book named Dr. Hakim, the pair have to work together through a backyard turned battlefield of oversized tools and toys to find a way back to their own bodies, and figure out what's actually worth saving."),
  dict(slug="cyberpunk-2077", title="Cyberpunk 2077", tagline="V chases immortality with a dead legend's ghost in their head.",
       release="2020-12-10", genres=["Action RPG"], platforms=["PC","PS5","PS4","Xbox"],
       developer="CD Projekt Red", publisher="CD Projekt", yt=("wrXNbZ19fPE","Cyberpunk 2077 Full Gameplay Walkthrough - No Commentary"),
       lore="A botched heist in Night City leaves mercenary V implanted with an experimental biochip carrying the digitized ghost of Johnny Silverhand, a rockerboy terrorist dead for fifty years and slowly overwriting V's own mind. Racing corporate fixers, gangs, and their own deteriorating body, V and Johnny have to find a way to separate before there's only room left for one of them."),
  dict(slug="the-last-of-us-part-2", title="The Last of Us Part II", tagline="Ellie's search for vengeance spirals across a ruined Seattle.",
       release="2020-06-19", genres=["Action Adventure"], platforms=["PS4","PS5"],
       developer="Naughty Dog", publisher="Sony Interactive Entertainment", yt=("x7dZRIhnsWc","The Last of Us Part 2 Gameplay Walkthrough FULL GAME (No Commentary)"),
       lore="Years after Joel's choice in Salt Lake City, a brutal act of violence in Jackson sends Ellie out on a vengeance-driven trek to Seattle, where a militia and a religious cult are already tearing each other apart amid the infected. The story splits its lens between hunter and hunted, forcing a hard look at what the cycle of retaliation actually costs everyone caught in it."),
  dict(slug="hades", title="Hades", tagline="Zagreus fights his way out of the Underworld, again and again.",
       release="2020-09-17", genres=["Roguelike"], platforms=["PC","Switch","PS4","PS5","Xbox"],
       developer="Supergiant Games", publisher="Supergiant Games", yt=("2cTCKCD0o4Y","HADES Full Walkthrough Gameplay – Xbox Series X 4K/60FPS No Commentary"),
       lore="Determined to escape his father's kingdom and find his missing mother, Zagreus, prince of the Underworld, hurls himself repeatedly at the halls of Hell, armed with weapons and blessings from the Olympians watching from above. Every failed run peels back another layer of Greek myth and family dysfunction, turning death itself into the game's core storytelling device."),
  dict(slug="ghost-of-tsushima", title="Ghost of Tsushima", tagline="A samurai abandons honor to save his island from the Mongols.",
       release="2020-07-17", genres=["Action Adventure"], platforms=["PS4","PS5","PC"],
       developer="Sucker Punch Productions", publisher="Sony Interactive Entertainment", yt=("7aTPqvOquiU","GHOST OF TSUSHIMA Gameplay Walkthrough FULL GAME (4K 60FPS) No Commentary"),
       lore="In 1274, the Mongol Empire's first invasion of Japan crushes the samurai defending Tsushima Island, leaving Jin Sakai the last of his clan standing. To have any chance of driving the invaders out, Jin abandons the samurai code that raised him for the stealth and subterfuge of the Ghost, a choice that costs him standing with his own people even as it wins him the war."),
  dict(slug="final-fantasy-7-remake", title="Final Fantasy VII Remake", tagline="AVALANCHE fights Shinra for the soul of Midgar.",
       release="2020-04-10", genres=["Action RPG"], platforms=["PS4","PS5","PC"],
       developer="Square Enix", publisher="Square Enix", yt=("F3hFd1WEz6U","Final Fantasy VII Remake Full Gameplay Walkthrough - No Commentary [4]"),
       lore="Mercenary Cloud Strife takes a job with the eco-terrorist group AVALANCHE, bombing the mako reactors draining the dying planet beneath the plate-city of Midgar. As Shinra's retaliation escalates and a mysterious flower girl named Aerith is pulled into the fight, Cloud's fragmented memories of his past start bleeding into a present that seems to be rewriting itself around him."),
  dict(slug="animal-crossing-new-horizons", title="Animal Crossing: New Horizons", tagline="Build a deserted island into a home, at your own pace.",
       release="2020-03-20", genres=["Life Simulation"], platforms=["Switch"],
       developer="Nintendo EPD", publisher="Nintendo", yt=("3KP9n4DKdSA","ANIMAL CROSSING NEW HORIZONS Gameplay Walkthrough FULL GAME (4K 60FPS) No Commentary"),
       lore="Signing up for Tom Nook's deserted island getaway package, a lone villager arrives with nothing but a tent and starts turning an empty island into a working town, one bridge, museum donation, and neighbor at a time. There's no real ending, only seasons and holidays looping year over year while the island, and whoever moves in beside you, keeps changing shape."),
  dict(slug="persona-5-royal", title="Persona 5 Royal", tagline="Tokyo's Phantom Thieves steal the twisted hearts of adults.",
       release="2020-03-31", genres=["JRPG"], platforms=["PS4","Switch","PC","Xbox"],
       developer="Atlus", publisher="Atlus", yt=("2B7jq74NS4g","PERSONA 5 ROYAL Gameplay Walkthrough FULL GAME (HD) No Commentary 100%"),
       lore="Falsely branded a criminal and transferred to a new Tokyo high school, a nameless protagonist discovers a power to summon a rebellious inner Persona and enter the corrupted psyches of abusive adults. Banding together as the Phantom Thieves of Hearts, he and his classmates steal the distorted desires driving their targets, turning teenage outcasts into the city's most wanted vigilantes."),
  dict(slug="half-life-alyx", title="Half-Life: Alyx", tagline="Alyx Vance fights the Combine occupation, years before Half-Life 2.",
       release="2020-03-23", genres=["VR Shooter"], platforms=["PC (VR)"],
       developer="Valve", publisher="Valve", yt=("-YbeCtIsuTU","HALF LIFE ALYX Gameplay Walkthrough FULL GAME (4K 60FPS) No Commentary"),
       lore="Set between the events of Half-Life and Half-Life 2, Alyx Vance and her father Eli lead the resistance against the alien Combine's occupation of Earth from the ruins of City 17. When Eli is captured, Alyx has to infiltrate Combine territory alone, uncovering just how deep the alien empire's control over the planet, and its interest in the Vances specifically, actually runs."),
  dict(slug="assassins-creed-valhalla", title="Assassin's Creed Valhalla", tagline="Eivor carves out a new home in Viking-age England.",
       release="2020-11-10", genres=["Action RPG"], platforms=["PC","PS4","PS5","Xbox"],
       developer="Ubisoft Montreal", publisher="Ubisoft", yt=("epB2bzGn90k","ASSASSIN'S CREED VALHALLA Gameplay Walkthrough FULL GAME [PS5 4K 60FPS] - No Commentary"),
       lore="Fleeing a homeland torn by clan warfare, Viking raider Eivor leads their clan across the sea to settle in England, forging alliances and rivalries with Saxon kings and rival Norse settlers alike. Beneath the raids and politics, an ancient conflict between the Hidden Ones and the Order of the Ancients resurfaces, pulling Eivor into a war that predates the Vikings by centuries."),
  dict(slug="sekiro", title="Sekiro: Shadows Die Twice", tagline="A disgraced shinobi hunts down his lord's kidnappers.",
       release="2019-03-22", genres=["Action Adventure"], platforms=["PC","PS4","Xbox"],
       developer="FromSoftware", publisher="Activision", yt=("pjt_dk3K9oo","SEKIRO SHADOWS DIE TWICE Full Game Walkthrough - No Commentary (#SekiroShadowsDieTwice) 2019"),
       lore="Left for dead and missing an arm after failing to protect his young lord, the shinobi known as Wolf is rebuilt with a prosthetic arm by a mysterious sculptor and sent back into war-torn Sengoku-era Japan. Hunting the samurai clan that took his lord and the immortality-granting bloodline they're after, Wolf has to decide how much of his humanity he's willing to trade to finish the job."),
  dict(slug="zelda-breath-of-the-wild", title="The Legend of Zelda: Breath of the Wild", tagline="Link wakes with no memory in a Hyrule long since fallen.",
       release="2017-03-03", genres=["Action Adventure"], platforms=["Switch","Wii U"],
       developer="Nintendo EPD", publisher="Nintendo", yt=("Vf5qecc1Uw0","ZELDA BREATH OF THE WILD Gameplay Walkthrough FULL GAME (4K 60FPS) No Commentary"),
       lore="A hundred years after Calamity Ganon's return laid waste to Hyrule and its Guardian army, Link wakes from a century of healing sleep with almost no memory of what happened. Guided by a spirit calling herself Zelda, he sets out across an open, ruined kingdom to free the four Divine Beasts and finally put an end to the calamity he apparently failed to stop the first time."),
  dict(slug="horizon-zero-dawn", title="Horizon Zero Dawn", tagline="A hunter uncovers why the world is ruled by machines.",
       release="2017-02-28", genres=["Action RPG"], platforms=["PS4","PC"],
       developer="Guerrilla Games", publisher="Sony Interactive Entertainment", yt=("kotCxZK_dTk","Horizon Zero Dawn Full Game Walkthrough - No Commentary (PC 4K UHD)"),
       lore="Centuries after civilization collapsed, humanity survives in scattered tribes sharing the land with vast robotic creatures roaming a re-wilded Earth. Outcast at birth, the hunter Aloy sets out to learn who her mother was and why she was abandoned, a search that uncovers the old-world catastrophe that made the machines, and the far more dangerous force some of them now serve."),
  dict(slug="hollow-knight", title="Hollow Knight", tagline="A silent knight descends into the ruined kingdom of Hallownest.",
       release="2017-02-24", genres=["Metroidvania"], platforms=["PC","Switch","PS4","Xbox"],
       developer="Team Cherry", publisher="Team Cherry", yt=("ZYc1frJQgs8","Hollow Knight FULL GAME Walkthrough Gameplay【No Commentary】4K 60FPS"),
       lore="Drawn to the sealed entrance of Hallownest, a nameless, silent bug descends into the fallen insect kingdom beneath the town of Dirtmouth. What starts as simple exploration uncovers a kingdom destroyed by an Infection born of its own royal Pale King's ambition, and a role the wandering knight may have been built to play in ending it."),
  dict(slug="spider-man", title="Marvel's Spider-Man", tagline="Eight years into the mask, Peter faces Mister Negative.",
       release="2018-09-07", genres=["Action Adventure"], platforms=["PS4","PS5"],
       developer="Insomniac Games", publisher="Sony Interactive Entertainment", yt=("W_tbAM-tIoE","SPIDERMAN PS4 Full Game Walkthrough - No Commentary (#Marvel's Spider-man Full Game) 2018"),
       lore="Eight years into his career as Spider-Man, an exhausted Peter Parker finally puts away Kingpin, only for the power vacuum to be filled by Mister Negative, whose ability to corrupt minds threatens the whole city, including people close to Peter. Balancing a crumbling personal life, Aunt May's work at a homeless shelter, and a growing rogues' gallery, Peter has to hold both his identities together as the city spins toward crisis."),
  dict(slug="god-of-war", title="God of War", tagline="Kratos leaves Greece behind to raise a son in Midgard.",
       release="2018-04-20", genres=["Action Adventure"], platforms=["PS4","PC"],
       developer="Santa Monica Studio", publisher="Sony Interactive Entertainment", yt=("E3f4UgBs_TQ","GOD OF WAR 2018 Gameplay Walkthrough FULL GAME [4K 60FPS] - No Commentary"),
       lore="Long after burning his way through the Greek pantheon, Kratos now lives quietly in the Norse realm of Midgard, until his wife Faye's death and dying wish send him and his son Atreus on a journey to scatter her ashes from the highest peak in all the realms. The trip drags a god trying to leave violence behind into the middle of Norse mythology's own coming apocalypse, with fatherhood as the real, harder fight underneath it."),
  dict(slug="red-dead-redemption-2", title="Red Dead Redemption 2", tagline="Arthur Morgan rides with a gang whose time has run out.",
       release="2018-10-26", genres=["Action Adventure"], platforms=["PC","PS4","Xbox"],
       developer="Rockstar Games", publisher="Rockstar Games", yt=("1nXH3Qdpi4o","RED DEAD REDEMPTION 2 Full Game Walkthrough - No Commentary (RDR 2 Full Game)"),
       lore="With the American frontier closing in around them, outlaw Arthur Morgan and the Van der Linde gang flee a botched robbery into the mountains, buying time they don't really have left. As lawmen, rival gangs, and cracks within the family itself close in, Arthur is forced to reckon with what decades of loyalty to Dutch van der Linde have actually cost him, and what little time he has left to make it right."),
  dict(slug="stardew-valley", title="Stardew Valley", tagline="Trade a cubicle for a broken-down farm and a small town.",
       release="2016-02-26", genres=["Farming Simulation"], platforms=["PC","Switch","PS4","Xbox","Mobile"],
       developer="ConcernedApe", publisher="ConcernedApe", yt=("1vsc98vUxxY","THE FULL BEGINNERS Guide for Stardew Valley"),
       lore="Burned out from a soulless corporate job, the player inherits their grandfather's overgrown farm in Stardew Valley and moves out to rebuild it from nothing. Between crops, mining, fishing, and a cast of townsfolk with their own quiet arcs, the valley's real threat turns out to be the corporate chain trying to buy up the community center at its heart."),
  dict(slug="dark-souls-3", title="Dark Souls III", tagline="An Ashen One is called to link the fading First Flame.",
       release="2016-03-24", genres=["Action RPG"], platforms=["PC","PS4","Xbox"],
       developer="FromSoftware", publisher="Bandai Namco", yt=("RmMbXC-NJEA","Dark Souls 3 Full Game Walkthrough - No Commentary (#DarkSouls3 Full Game) 2016"),
       lore="As the First Flame gutters out for what may be the last time, the undead Lords of Cinder who once sacrificed themselves to sustain it have abandoned their thrones, leaving the world of Lothric to decay. An Ashen One, risen from the grave, is sent to drag those Lords back to their seats of power and relink the fire, or let it die and see what comes after."),
  dict(slug="witcher-3", title="The Witcher 3: Wild Hunt", tagline="Geralt hunts his adopted daughter across a war-torn continent.",
       release="2015-05-19", genres=["RPG"], platforms=["PC","PS4","Xbox","Switch"],
       developer="CD Projekt Red", publisher="CD Projekt", yt=("nXi0hcbmWXk","THE WITCHER 3: WILD HUNT Gameplay Walkthrough FULL GAME [4K 60FPS] - No Commentary"),
       lore="With the Northern Kingdoms at war with Nilfgaard, monster hunter Geralt of Rivia searches for Ciri, the adopted daughter he trained as a witcher, before the spectral Wild Hunt finds her first. The search for Ciri weaves through a continent's worth of local tragedies and political schemes, with Geralt's choices along the way shaping just how much of it he can actually save."),
  dict(slug="fallout-4", title="Fallout 4", tagline="A vault dweller wakes 210 years late to find their son gone.",
       release="2015-11-10", genres=["Action RPG"], platforms=["PC","PS4","Xbox"],
       developer="Bethesda Game Studios", publisher="Bethesda Softworks", yt=("QrFVuF5Jqws","Fallout 4 - Full Game Story Walkthrough (No Commentary | 4K 60FPS)"),
       lore="Cryogenically frozen in Vault 111 during the bombs that ended the world, the Sole Survivor thaws out over two centuries later to find their spouse murdered and their infant son kidnapped. The search for Shaun leads through the irradiated ruins of the Commonwealth and its factions, the Brotherhood, the Institute, the Railroad, each with a very different idea of what should be built from what's left."),
  dict(slug="bloodborne", title="Bloodborne", tagline="A hunter chases a cure through the plague-lit streets of Yharnam.",
       release="2015-03-24", genres=["Action RPG"], platforms=["PS4"],
       developer="FromSoftware", publisher="Sony Interactive Entertainment", yt=("Fen45fJJ9Ko","Bloodborne - Longplay Full Game Walkthrough (No Commentary)"),
       lore="Arriving in the city of Yharnam seeking a blood-based cure, a nameless hunter finds the city already consumed by a beast-plague on the night of the hunt. What begins as a monster hunt spirals into cosmic horror, as the hunter uncovers the Healing Church's experiments into a world above the sky, and the price Yharnam's citizens paid for reaching toward it."),
  dict(slug="gta-5", title="Grand Theft Auto V", tagline="Three criminals, one impossible heist city.",
       release="2013-09-17", genres=["Action Adventure"], platforms=["PC","PS5","PS4","Xbox"],
       developer="Rockstar North", publisher="Rockstar Games", yt=("dt-zAC_-FMs","Grand Theft Auto V Enhanced Edition Gameplay Walkthrough Part 1 [PC 4K 60FPS] - No Commentary"),
       lore="Retired bank robber Michael, street hustler Franklin, and unhinged loose cannon Trevor cross paths in the sprawl of Los Santos, pulled together by a shared talent for heists and a shared distrust of everyone around them, including each other. Federal agents, rival gangs, and their own worse instincts keep dragging the trio back together for one more job neither of them can really afford to walk away from."),
  dict(slug="the-last-of-us", title="The Last of Us", tagline="A smuggler is hired to escort a girl across a ruined America.",
       release="2013-06-14", genres=["Action Adventure"], platforms=["PS3","PS4","PS5","PC"],
       developer="Naughty Dog", publisher="Sony Interactive Entertainment", yt=("Qv8RJVEjAyg","The Last of Us Remastered Walkthrough Gameplay Full Game – PS4 Pro No Commentary"),
       lore="Twenty years into a fungal pandemic that turned much of humanity into infected monsters, hardened smuggler Joel is hired to escort fourteen-year-old Ellie across a quarantined, collapsing country. Ellie's apparent immunity to the infection turns a simple courier job into a journey that reopens Joel's own buried grief, and eventually forces a choice about what he's actually willing to sacrifice for her."),
  dict(slug="portal-2", title="Portal 2", tagline="Chell wakes Aperture Science's AI, and its grudge, back up.",
       release="2011-04-19", genres=["Puzzle"], platforms=["PC","PS3","Xbox"],
       developer="Valve", publisher="Valve", yt=("o-luWQ5y53w","Portal 2 Full Game Walkthrough (No Commentary, 1080p 60FPS)"),
       lore="Woken from stasis decades after escaping the first Aperture Science test chambers, Chell finds the facility half-collapsed and, briefly, in the hands of the sarcastic AI Wheatley. When a botched rescue accidentally reboots the vengeful GLaDOS, the two AIs' rivalry drags Chell through both the ruined modern facility and its buried, decades-older predecessor."),
  dict(slug="minecraft", title="Minecraft", tagline="Punch a tree, and build absolutely anything from there.",
       release="2011-11-18", genres=["Sandbox Survival"], platforms=["PC","Mobile","Console","Switch"],
       developer="Mojang Studios", publisher="Mojang Studios", yt=("FC2czMA2Pjc","Minecraft Survival Java Edition - FULL GAME Walkthrough - No commentary"),
       lore="Dropped into a procedurally generated world with nothing but bare hands, a player has to punch trees, mine stone, and survive the monsters that spawn once night falls, building up toward tools, shelter, and eventually a portal to the hostile Nether. There's no fixed story beyond that loop; what gets built, and how far a given world goes toward defeating the End's dragon, is entirely up to whoever's playing."),
  dict(slug="skyrim", title="The Elder Scrolls V: Skyrim", tagline="A prisoner turns out to be Skyrim's prophesied Dragonborn.",
       release="2011-11-11", genres=["RPG"], platforms=["PC","PS3","Xbox","Switch","PS4","Xbox One"],
       developer="Bethesda Game Studios", publisher="Bethesda Softworks", yt=("nr62-GnrrOs","Skyrim - Longplay Main Quest Full Game Walkthrough (No Commentary)"),
       lore="Pulled from a prisoner transport moments before execution by the sudden return of dragons to Skyrim, an unnamed captive discovers they're Dragonborn, able to absorb a dragon's soul and shout with a dragon's power. Between a civil war splitting the province in two and the return of the world-eating dragon Alduin, the Dragonborn is dragged, however reluctantly, toward becoming the one thing standing between Skyrim and both."),
  dict(slug="terraria", title="Terraria", tagline="Dig, build, and fight your way from dirt to the stars.",
       release="2011-05-16", genres=["Sandbox Survival"], platforms=["PC","Mobile","Console","Switch"],
       developer="Re-Logic", publisher="Re-Logic", yt=("ZS9TFsc0jNQ","Terraria Guide for Beginners! Terraria Progression Guide for Casuals! Terraria Guide Walkthrough!"),
       lore="Dropped onto the surface of a freshly generated 2D world, a nameless adventurer digs down into caverns, biomes, and the Underworld while building up gear tough enough to survive progressively larger bosses. The loop of digging, crafting, and boss-fighting keeps escalating from wooden swords to weapons that can fight actual celestial invasions, with no fixed ending beyond how far a player wants to push it."),
  dict(slug="mass-effect-2", title="Mass Effect 2", tagline="Shepard, freshly resurrected, assembles a suicide-mission crew.",
       release="2010-01-26", genres=["Action RPG"], platforms=["PC","PS3","Xbox"],
       developer="BioWare", publisher="Electronic Arts", yt=("jL7ocFmmrQU","MASS EFFECT 2 Gameplay Walkthrough FULL GAME (4K 60FPS) No Commentary"),
       lore="Killed in the opening minutes and rebuilt by the shadowy pro-human group Cerberus, Commander Shepard is sent after a mysterious enemy abducting entire human colonies with no survivors left behind. Recruiting a crew of specialists across the galaxy for what everyone agrees is a one-way suicide mission, Shepard has to decide how much trust to put in Cerberus, and in a crew mostly loyal to their own causes first."),
  dict(slug="world-of-warcraft", title="World of Warcraft", tagline="Azeroth's endless war between Horde and Alliance, still going.",
       release="2004-11-23", genres=["MMORPG"], platforms=["PC"],
       developer="Blizzard Entertainment", publisher="Blizzard Entertainment", yt=("igrq4lf1eWw","World of Warcraft Complete Beginner Guide 2026 For Returning & New Players | Midnight"),
       lore="Set generations after the Second War left Azeroth divided, World of Warcraft drops players into the ongoing struggle between the Horde and the Alliance, playable across dozens of races and classes with their own history in the setting. Two decades and more than a dozen expansions later, the same core conflict has expanded across shattered continents, the Twisting Nether, and time itself, without ever fully resolving."),
]

def slugify_check():
    seen = set()
    for g in GAMES:
        assert g["slug"] not in seen, g["slug"]
        seen.add(g["slug"])

def main():
    slugify_check()
    out = []
    for g in GAMES:
        accent, accent2 = GENRE_ACCENT.get(g["genres"][0], ("#8fd3ff", "#2a5a9e"))
        out.append({
            "slug": g["slug"],
            "title": g["title"],
            "tagline": g["tagline"],
            "releaseDate": g["release"],
            "genres": g["genres"],
            "platforms": g["platforms"],
            "developer": g["developer"],
            "publisher": g["publisher"],
            "accent": accent,
            "accent2": accent2,
            "youtube": {"id": g["yt"][0], "title": g["yt"][1]},
            "lore": {
                "en": g["lore"],
                "de": "",
                "es": "",
                "fr": ""
            }
        })
    out.sort(key=lambda x: x["releaseDate"], reverse=True)
    os.makedirs("data", exist_ok=True)
    with open("data/games.json", "w") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print(f"Wrote {len(out)} games to data/games.json")

if __name__ == "__main__":
    main()
